# Generated by Django 3.2.8 on 2022-03-02 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LatestPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Price', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductQuality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quality', models.CharField(blank=True, max_length=100, null=True)),
                ('Price', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product', models.CharField(blank=True, max_length=100)),
                ('Material_Type', models.CharField(choices=[('N', 'Natural'), ('M', 'Manufactured')], default=1, max_length=1)),
                ('GST', models.CharField(blank=True, max_length=20, null=True)),
                ('Ton', models.CharField(blank=True, max_length=20, null=True)),
                ('HSNCode', models.CharField(blank=True, max_length=20, null=True)),
                ('AvgPrice', models.CharField(blank=True, max_length=20)),
                ('LatestPrice', models.ManyToManyField(blank=True, to='products.LatestPrice')),
                ('Quality', models.ManyToManyField(blank=True, to='products.ProductQuality')),
                ('Vendor', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='vendors.vendor')),
            ],
        ),
    ]
