# Generated by Django 3.2.12 on 2022-04-28 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0006_auto_20220428_1100'),
        ('products', '0002_product_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Material_Supplying',
            field=models.ManyToManyField(blank=True, to='vendors.Material_Supplying'),
        ),
    ]
