# Generated by Django 3.2.12 on 2022-04-01 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_date_alter_materialorder_others_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='Date',
            field=models.DateField(auto_now=True),
        ),
    ]
