# Generated by Django 3.2.8 on 2022-03-02 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        ('customers', '0001_initial'),
        ('agency', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerQuotationDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customerName', models.CharField(blank=True, max_length=100)),
                ('customerCompany', models.CharField(blank=True, max_length=100)),
                ('customerAddress', models.CharField(blank=True, max_length=100)),
                ('customerPosition', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerQuotationTerms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advance', models.CharField(blank=True, max_length=100)),
                ('days', models.CharField(blank=True, max_length=100)),
                ('generateDate', models.CharField(blank=True, max_length=100)),
                ('gstType', models.CharField(blank=True, max_length=50)),
                ('detail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quotations.customerquotationdetail')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseQuotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published', models.DateTimeField(auto_now_add=True)),
                ('material', models.ManyToManyField(blank=True, to='orders.MaterialOrder')),
            ],
        ),
        migrations.CreateModel(
            name='VendorQuotationDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(blank=True, max_length=100)),
                ('mat_id', models.ManyToManyField(blank=True, to='orders.MaterialOrder')),
            ],
        ),
        migrations.CreateModel(
            name='SalesQuotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer')),
                ('po', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.ponumber')),
                ('po_materials', models.ManyToManyField(blank=True, to='orders.POMaterialInfo')),
            ],
        ),
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customerGenerate', models.BooleanField(default=False)),
                ('vendorGenerate', models.BooleanField(default=False)),
                ('published', models.DateTimeField(auto_now_add=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agency.agency')),
                ('customerInfo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quotations.customerquotationterms')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quotations.purchasequotation')),
                ('sales', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quotations.salesquotation')),
                ('vendorInfo', models.ManyToManyField(blank=True, to='quotations.VendorQuotationDetail')),
            ],
        ),
    ]
