# Generated by Django 3.2.12 on 2022-05-08 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerquotationterms',
            name='NonGstTerms',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendorquotationdetail',
            name='VendorGstTerms',
            field=models.TextField(blank=True, null=True),
        ),
    ]
