# Generated by Django 3.2.8 on 2022-03-09 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('purchase', '0001_initial'),
        ('orders', '0001_initial'),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customerid', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='customers.customer')),
                ('gst', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='customers.customergstbillingaddress')),
                ('pan', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='customers.panno')),
                ('phone', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='customers.customerphonenumber')),
                ('tin', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='customers.tinno')),
            ],
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_invoice', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='sales.customerinfo')),
                ('netAmount', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='purchase.purchasenetamount')),
                ('orderid', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
            ],
        ),
        migrations.CreateModel(
            name='Total',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cgst', models.CharField(blank=True, max_length=100)),
                ('sgst', models.CharField(blank=True, max_length=100)),
                ('roundedoff', models.CharField(blank=True, max_length=100)),
                ('total', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SalesMaterialInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.CharField(blank=True, max_length=100)),
                ('CDC', models.CharField(blank=True, max_length=100)),
                ('LDC', models.CharField(blank=True, max_length=100)),
                ('Formula', models.CharField(blank=True, max_length=100)),
                ('qty', models.CharField(blank=True, max_length=100)),
                ('Moisture', models.CharField(blank=True, max_length=100)),
                ('VehicleNo', models.CharField(blank=True, max_length=100)),
                ('RoundOff', models.CharField(blank=True, max_length=100)),
                ('Total', models.CharField(blank=True, max_length=100)),
                ('WithGST', models.CharField(blank=True, max_length=100)),
                ('SiteSupervisior', models.CharField(blank=True, max_length=100)),
                ('QC', models.CharField(blank=True, max_length=100)),
                ('Security', models.CharField(blank=True, max_length=100)),
                ('Engineer', models.CharField(blank=True, max_length=100)),
                ('DriverName', models.CharField(blank=True, max_length=100)),
                ('UnloadingSupervisior', models.CharField(blank=True, max_length=100)),
                ('orderId', models.CharField(blank=True, max_length=100)),
                ('ig', models.BooleanField(default=False)),
                ('MatId', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='orders.materialorder')),
            ],
        ),
        migrations.CreateModel(
            name='SalesCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderid', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
                ('sales', models.ManyToManyField(blank=True, to='sales.Sales')),
            ],
        ),
        migrations.AddField(
            model_name='sales',
            name='poInfo',
            field=models.ManyToManyField(blank=True, to='sales.SalesMaterialInfo'),
        ),
        migrations.AddField(
            model_name='sales',
            name='remainder',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='purchase.purchaseremainder'),
        ),
    ]
