# Generated by Django 4.0.1 on 2022-03-10 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='doc',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
