# Generated by Django 3.2.8 on 2022-03-02 18:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgencyBankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Account_Holder_Name', models.CharField(blank=True, max_length=100, null=True)),
                ('Account_Holder_Position', models.CharField(blank=True, max_length=100, null=True)),
                ('Account_Number', models.CharField(blank=True, max_length=100, null=True)),
                ('IFSC_Code', models.CharField(blank=True, max_length=100, null=True)),
                ('Branch', models.CharField(blank=True, max_length=100, null=True)),
                ('Bank_Name', models.CharField(blank=True, max_length=100, null=True)),
                ('Register_Email', models.CharField(blank=True, max_length=100, null=True)),
                ('Register_Phone', models.CharField(blank=True, max_length=100, null=True)),
                ('Timestamp', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AgencyCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Certificate_Name', models.CharField(blank=True, max_length=100, null=True)),
                ('Certificate_Scan_Copy', models.FileField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/')),
                ('Timestamp', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AgencyPhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Phone', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Signature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('signature', models.ImageField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/')),
            ],
        ),
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=100, null=True)),
                ('Email', models.CharField(blank=True, max_length=100, null=True)),
                ('Logo', models.FileField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/')),
                ('Active', models.BooleanField(default=False)),
                ('Timestamp', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
                ('GST_Number', models.CharField(blank=True, max_length=100, null=True)),
                ('PAN_Number', models.CharField(blank=True, max_length=100, null=True)),
                ('Address', models.CharField(blank=True, max_length=100, null=True)),
                ('City', models.CharField(blank=True, max_length=100, null=True)),
                ('Zip', models.CharField(blank=True, max_length=100, null=True)),
                ('State', models.CharField(blank=True, max_length=100, null=True)),
                ('Country', models.CharField(blank=True, max_length=100, null=True)),
                ('Location_Url', models.CharField(blank=True, max_length=100, null=True)),
                ('Tin', models.CharField(blank=True, max_length=100, null=True)),
                ('Bank_Account', models.ManyToManyField(blank=True, to='agency.AgencyBankAccount')),
                ('Certificates', models.ManyToManyField(blank=True, to='agency.AgencyCertificate')),
                ('Phone', models.ManyToManyField(blank=True, to='agency.AgencyPhone')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-Timestamp'],
            },
        ),
    ]
