# Generated by Django 4.0.1 on 2022-03-09 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='Date',
            field=models.DateField(auto_now=True),
        ),
    ]
