# Generated by Django 4.0.1 on 2022-03-12 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0002_agency_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agency',
            name='Date',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
