# Generated by Django 3.2.12 on 2022-04-27 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0003_alter_agency_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='agencyphone',
            name='ph_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
