# Generated by Django 3.2.8 on 2022-03-02 18:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Payment_Term', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BranchDeliveryAddres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Address', models.CharField(blank=True, max_length=100, null=True)),
                ('City', models.CharField(blank=True, max_length=100, null=True)),
                ('State', models.CharField(blank=True, max_length=100, null=True)),
                ('Zip', models.CharField(blank=True, max_length=100, null=True)),
                ('Country', models.CharField(blank=True, max_length=100, null=True)),
                ('NickName', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerBankAccounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Account_Holder_Name', models.CharField(blank=True, max_length=100, null=True)),
                ('Account_Category', models.CharField(blank=True, choices=[('0', 'Personal'), ('1', 'Registered Account')], default=0, max_length=1, null=True)),
                ('Account_No', models.CharField(blank=True, max_length=100, null=True)),
                ('Account_Position', models.CharField(blank=True, max_length=100, null=True)),
                ('IFSC_Code', models.CharField(blank=True, max_length=100, null=True)),
                ('Branch', models.CharField(blank=True, max_length=100, null=True)),
                ('Register_Phone', models.CharField(blank=True, max_length=100, null=True)),
                ('Register_Email', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerCertifcate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Certificate_Name', models.CharField(blank=True, max_length=100, null=True)),
                ('Scan_Copy', models.FileField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerDeliveryAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Customer_Name', models.CharField(blank=True, max_length=200, null=True)),
                ('Branch', models.CharField(blank=True, max_length=200, null=True)),
                ('URL_Location_Of_The_Unloading_Place', models.CharField(blank=True, max_length=200, null=True)),
                ('URL_Office_Location', models.CharField(blank=True, max_length=200, null=True)),
                ('URL_Of_Owner_House', models.CharField(blank=True, max_length=200, null=True)),
                ('Invoice_Submitting_URL', models.CharField(blank=True, max_length=200, null=True)),
                ('Payment_Collecting_URL', models.CharField(blank=True, max_length=200, null=True)),
                ('Add_other_URL', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerGSTBillingAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Leggal_Name', models.CharField(blank=True, max_length=100, null=True)),
                ('Trade_Name', models.CharField(blank=True, max_length=100, null=True)),
                ('GST_No', models.CharField(blank=True, max_length=100, null=True)),
                ('Scan_Copy', models.FileField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/')),
                ('Address', models.CharField(blank=True, max_length=100, null=True)),
                ('City', models.CharField(blank=True, max_length=20, null=True)),
                ('State', models.CharField(blank=True, max_length=30, null=True)),
                ('Zip', models.CharField(blank=True, max_length=10, null=True)),
                ('Country', models.CharField(blank=True, max_length=30, null=True)),
                ('Location_Url', models.URLField(blank=True, max_length=100, null=True)),
                ('Mobile', models.CharField(blank=True, max_length=20, null=True)),
                ('Mail_Id', models.CharField(blank=True, max_length=50, null=True)),
                ('GST_Bank', models.CharField(blank=True, max_length=50, null=True)),
                ('GST_Branch', models.CharField(blank=True, max_length=50, null=True)),
                ('IFSC', models.CharField(blank=True, max_length=50, null=True)),
                ('Holder_Name', models.CharField(blank=True, max_length=50, null=True)),
                ('Position', models.CharField(blank=True, max_length=50, null=True)),
                ('Photo', models.FileField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerPhoneNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Phone_Number', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=100, null=True)),
                ('Contact_No', models.CharField(blank=True, max_length=20, null=True)),
                ('Email', models.EmailField(blank=True, max_length=30, null=True)),
                ('Position', models.CharField(choices=[('PH', 'Purchase Head'), ('AH', 'Account Head'), ('QH', 'QC Head'), ('PU', 'Payment Head'), ('US', 'Unloading Suprivisor'), ('SP', 'Security')], max_length=2)),
                ('Location', models.CharField(blank=True, max_length=100, null=True)),
                ('City', models.CharField(blank=True, max_length=50, null=True)),
                ('Zip', models.CharField(blank=True, max_length=50, null=True)),
                ('State', models.CharField(blank=True, max_length=50, null=True)),
                ('Country', models.CharField(blank=True, max_length=50, null=True)),
                ('Photo', models.FileField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/')),
            ],
        ),
        migrations.CreateModel(
            name='PANNo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PAN_No', models.CharField(blank=True, max_length=100, null=True)),
                ('PAN_Scan_Copy', models.FileField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/')),
            ],
        ),
        migrations.CreateModel(
            name='TINNo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TIN_No', models.CharField(blank=True, max_length=100, null=True)),
                ('Scan_Copy', models.FileField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Company_Name', models.CharField(blank=True, max_length=100, null=True)),
                ('Company_Address', models.CharField(blank=True, max_length=100, null=True)),
                ('Company_Email', models.EmailField(blank=True, max_length=100, null=True)),
                ('Company_Logo', models.FileField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/')),
                ('Company_City', models.CharField(blank=True, max_length=100, null=True)),
                ('Company_State', models.CharField(blank=True, max_length=100, null=True)),
                ('Company_Zip', models.CharField(blank=True, max_length=100, null=True)),
                ('Company_Country', models.CharField(blank=True, max_length=100, null=True)),
                ('Founder_Name', models.CharField(blank=True, max_length=100, null=True)),
                ('Founder_Email', models.CharField(blank=True, max_length=50, null=True)),
                ('Founder_Address', models.TextField(blank=True, null=True)),
                ('Founder_City', models.CharField(blank=True, max_length=100, null=True)),
                ('Founder_State', models.CharField(blank=True, max_length=100, null=True)),
                ('Founder_Zip', models.CharField(blank=True, max_length=100, null=True)),
                ('Founder_Country', models.CharField(blank=True, max_length=100, null=True)),
                ('GST_Type', models.CharField(blank=True, choices=[('0', 'GST Registered'), ('1', 'Unregistered')], max_length=1)),
                ('No_Of_Project', models.CharField(blank=True, max_length=10, null=True)),
                ('Remarks', models.TextField(blank=True, null=True)),
                ('Payment_Terms', models.CharField(blank=True, max_length=100, null=True)),
                ('published', models.DateTimeField(auto_now_add=True)),
                ('Bank_Account', models.ManyToManyField(blank=True, to='customers.CustomerBankAccounts')),
                ('Branches', models.ManyToManyField(blank=True, to='customers.Branch')),
                ('Certificate', models.ManyToManyField(blank=True, to='customers.CustomerCertifcate')),
                ('Customer_Staff_Account', models.ManyToManyField(blank=True, to='customers.CustomerStaff')),
                ('Founder_Phone', models.ManyToManyField(blank=True, to='customers.CustomerPhoneNumber')),
                ('GST_No', models.ManyToManyField(blank=True, to='customers.CustomerGSTBillingAddress')),
                ('PAN_No', models.ManyToManyField(blank=True, to='customers.PANNo')),
                ('TIN_No', models.ManyToManyField(blank=True, to='customers.TINNo')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='branch',
            name='Billing_Address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customers.customergstbillingaddress'),
        ),
        migrations.AddField(
            model_name='branch',
            name='Delivery_Address',
            field=models.ManyToManyField(blank=True, to='customers.BranchDeliveryAddres'),
        ),
        migrations.AddField(
            model_name='branch',
            name='Staff_Detail',
            field=models.ManyToManyField(blank=True, to='customers.CustomerStaff'),
        ),
    ]
