# Generated by Django 3.2.12 on 2022-04-29 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_auto_20220428_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branchdeliveryaddres',
            name='Address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='Company_Address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customergstbillingaddress',
            name='Address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customerstaff',
            name='Location',
            field=models.TextField(blank=True, null=True),
        ),
    ]
