# Generated by Django 3.2.8 on 2022-03-02 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('voucher', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Post_Date', models.DateField()),
                ('Value_Date', models.DateField()),
                ('Entry', models.CharField(blank=True, max_length=100, null=True)),
                ('Name', models.CharField(blank=True, max_length=100, null=True)),
                ('Remitance_Branch', models.CharField(blank=True, max_length=100, null=True)),
                ('Total_Amount', models.CharField(blank=True, max_length=100, null=True)),
                ('Cheque_No', models.CharField(blank=True, max_length=100, null=True)),
                ('GST_Type', models.CharField(blank=True, max_length=100, null=True)),
                ('Person_Type', models.CharField(blank=True, max_length=100, null=True)),
                ('Expence_Type', models.CharField(blank=True, max_length=100, null=True)),
                ('Transaction_Type', models.CharField(blank=True, max_length=100, null=True)),
                ('Transaction_Amount', models.CharField(blank=True, max_length=100, null=True)),
                ('Net_Balance_Amount', models.CharField(blank=True, max_length=100, null=True)),
                ('GST_Balance_Amount', models.CharField(blank=True, max_length=100, null=True)),
                ('Remarks', models.TextField(blank=True, null=True)),
                ('Description', models.TextField(blank=True, null=True)),
                ('Date', models.DateField(auto_now=True)),
                ('voucherId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='voucher.vourchersamount')),
            ],
        ),
    ]
