# Generated by Django 3.2.12 on 2022-05-09 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankentries', '0002_auto_20220415_0904'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankentry',
            name='Payment_Mode',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
