# Generated by Django 4.0.1 on 2022-04-15 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='purchase_entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_company', models.CharField(blank=True, max_length=200, null=True)),
                ('sales_company', models.CharField(blank=True, max_length=200, null=True)),
                ('billing_address', models.TextField(blank=True, null=True)),
                ('delivery_address', models.TextField(blank=True, null=True)),
                ('material', models.CharField(blank=True, max_length=200, null=True)),
                ('calculation', models.IntegerField(blank=True, null=True)),
                ('quantity_type', models.CharField(blank=True, max_length=200, null=True)),
                ('quantity', models.CharField(blank=True, max_length=200, null=True)),
                ('round_off', models.CharField(blank=True, max_length=100, null=True)),
                ('total_quantity', models.CharField(blank=True, max_length=100, null=True)),
                ('price', models.CharField(blank=True, max_length=100, null=True)),
                ('amount', models.CharField(blank=True, max_length=100, null=True)),
                ('amount_paid', models.CharField(blank=True, max_length=100, null=True)),
                ('amount_balance', models.CharField(blank=True, max_length=100, null=True)),
                ('voucher', models.CharField(blank=True, max_length=100, null=True)),
                ('dc_scan_copy', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('purchase_bill', models.CharField(blank=True, max_length=100, null=True)),
                ('purchase_entry_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='sales_entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sales_entry_date', models.DateField()),
                ('purchase_company', models.CharField(blank=True, max_length=200, null=True)),
                ('sales_company', models.CharField(blank=True, max_length=200, null=True)),
                ('billing_address', models.TextField(blank=True, null=True)),
                ('delivery_address', models.TextField(blank=True, null=True)),
                ('material', models.CharField(blank=True, max_length=200, null=True)),
                ('calculation', models.IntegerField(blank=True, null=True)),
                ('quantity_type', models.CharField(blank=True, max_length=200, null=True)),
                ('quantity', models.CharField(blank=True, max_length=200, null=True)),
                ('round_off', models.CharField(blank=True, max_length=100, null=True)),
                ('total_quantity', models.CharField(blank=True, max_length=100, null=True)),
                ('price', models.CharField(blank=True, max_length=100, null=True)),
                ('amount', models.CharField(blank=True, max_length=100, null=True)),
                ('amount_paid', models.CharField(blank=True, max_length=100, null=True)),
                ('amount_balance', models.CharField(blank=True, max_length=100, null=True)),
                ('invoice', models.CharField(blank=True, max_length=100, null=True)),
                ('dc_scan_copy', models.ImageField(upload_to='media/')),
            ],
        ),
    ]
