# Generated by Django 3.2.12 on 2022-04-18 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cashregister', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase_entry',
            old_name='purchase_entry_date',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='purchase_entry',
            name='calculation',
        ),
    ]
