# Generated by Django 3.2.8 on 2022-03-02 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Asset_Type', models.CharField(max_length=100)),
                ('Asset_Name', models.CharField(max_length=100)),
                ('Asset_Value', models.CharField(max_length=100)),
                ('Date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExpenceCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Expences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Expence_Name', models.CharField(max_length=100)),
                ('Payment_Mode', models.CharField(max_length=100)),
                ('Payment_Type', models.CharField(max_length=100)),
                ('Amount', models.CharField(max_length=100)),
                ('Date', models.DateField()),
                ('Bill_Reference', models.FileField(blank=True, max_length=500, null=True, upload_to='uploads/%Y/%m/%d/')),
                ('Expence_Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expences.expencecategories')),
            ],
        ),
    ]
