# Generated by Django 3.2.12 on 2022-04-17 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0003_alter_agency_date'),
        ('expences', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assets',
            name='Agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agency.agency'),
        ),
        migrations.AddField(
            model_name='expences',
            name='Agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agency.agency'),
        ),
    ]
