# Generated by Django 3.2.12 on 2022-04-18 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0003_alter_agency_date'),
        ('expences', '0002_auto_20220417_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='expencecategories',
            name='Agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agency.agency'),
        ),
    ]
