# Generated by Django 4.0.1 on 2022-03-14 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='doc',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
