# Generated by Django 3.2.12 on 2022-04-15 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_filemanagement_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filemanagement',
            name='File',
            field=models.FileField(upload_to='files'),
        ),
    ]
