# Generated by Django 3.2.8 on 2022-03-02 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendors', '0001_initial'),
        ('quotations', '0001_initial'),
        ('purchase', '0001_initial'),
        ('agency', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VoucherDate', models.CharField(blank=True, max_length=50)),
                ('VoucherNo', models.CharField(blank=True, max_length=50)),
                ('VoucherSLNo', models.CharField(blank=True, max_length=50)),
                ('InvoiceNo', models.CharField(blank=True, max_length=50)),
                ('DebitVoucherNo', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='VourchersAmount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.CharField(blank=True, max_length=50)),
                ('cgst_amount', models.CharField(blank=True, max_length=50)),
                ('sgst_amount', models.CharField(blank=True, max_length=50)),
                ('total_amount', models.CharField(blank=True, max_length=50)),
                ('bank_entries', models.BooleanField(default=False)),
                ('Info', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='voucher.purchaseinfo')),
                ('VoucherMaterialInfo', models.ManyToManyField(blank=True, to='purchase.PurchaseMaterialEntry')),
            ],
        ),
        migrations.CreateModel(
            name='VoucherVendorInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=50)),
                ('AcNumber', models.CharField(blank=True, max_length=50)),
                ('Bank', models.CharField(blank=True, max_length=50)),
                ('IFSC', models.CharField(blank=True, max_length=50)),
                ('Mobile', models.CharField(blank=True, max_length=50)),
                ('PanNo', models.CharField(blank=True, max_length=50)),
                ('GSTNo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vendors.vendorgst')),
            ],
        ),
        migrations.CreateModel(
            name='VoucherSignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signature_name', models.CharField(blank=True, choices=[('0', 'Prepared By'), ('1', 'Approved By'), ('2', 'Passed By')], max_length=1)),
                ('signature_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agency.signature')),
            ],
        ),
        migrations.CreateModel(
            name='VoucherDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(auto_now=True)),
                ('VendorId', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='vendors.vendor')),
                ('amount', models.ManyToManyField(blank=True, to='voucher.VourchersAmount')),
                ('quotation', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='quotations.quotation')),
                ('signature', models.ManyToManyField(blank=True, to='voucher.VoucherSignature')),
                ('vendorDetail', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='voucher.vouchervendorinfo')),
            ],
        ),
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(auto_now=True)),
                ('purchase', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='purchase.purchaseentry')),
                ('quotation', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='quotations.quotation')),
                ('voucher', models.ManyToManyField(blank=True, to='voucher.VoucherDetail')),
            ],
        ),
    ]
