# Generated by Django 4.0.1 on 2022-03-12 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0002_vendor_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='Vendor_Category',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
