# Generated by Django 4.0.1 on 2022-03-23 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0003_alter_vendor_vendor_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='Material_Supplying',
            field=models.ManyToManyField(blank=True, to='vendors.Material_Supplying'),
        ),
    ]
