# Generated by Django 3.2.12 on 2022-04-27 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0004_alter_vendor_material_supplying'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material_from',
            name='Type',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
