# Generated by Django 3.2.12 on 2022-04-28 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0005_alter_material_from_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material_from',
            name='Email',
        ),
        migrations.RemoveField(
            model_name='material_from',
            name='Phone',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='Material_From',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='Material_To',
        ),
        migrations.AddField(
            model_name='material_supplying',
            name='Material_From',
            field=models.ManyToManyField(blank=True, to='vendors.Material_From'),
        ),
        migrations.AddField(
            model_name='material_supplying',
            name='Material_To',
            field=models.ManyToManyField(blank=True, to='vendors.Material_To'),
        ),
    ]
