# Generated by Django 4.0.1 on 2022-04-18 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sales', '0001_initial'),
        ('orders', '0001_initial'),
        ('agency', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DCDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_name', models.CharField(blank=True, max_length=100)),
                ('dcNo', models.CharField(blank=True, max_length=100)),
                ('dcdate', models.CharField(blank=True, max_length=100)),
                ('hsc', models.CharField(blank=True, max_length=100)),
                ('quantity', models.CharField(blank=True, max_length=100)),
                ('rate', models.CharField(blank=True, max_length=100)),
                ('per', models.CharField(blank=True, max_length=100)),
                ('amount', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SingleSalesInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('InvoiceNo', models.CharField(blank=True, max_length=100)),
                ('InvoiceDate', models.CharField(blank=True, max_length=100)),
                ('OtherReference', models.CharField(blank=True, max_length=100)),
                ('SupplierRef', models.CharField(blank=True, max_length=100)),
                ('TermsPayment', models.CharField(blank=True, max_length=100)),
                ('DeliveryNote', models.CharField(blank=True, max_length=100)),
                ('Destination', models.CharField(blank=True, max_length=100)),
                ('DespatchDocumentNo', models.CharField(blank=True, max_length=100)),
                ('BankAccount', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='agency.agencybankaccount')),
                ('DC', models.ManyToManyField(blank=True, to='invoice.DCDetail')),
                ('orderid', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
                ('phone', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='agency.agencyphone')),
                ('saleid', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='sales.sales')),
            ],
        ),
        migrations.CreateModel(
            name='SalesInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(auto_now=True)),
                ('invoice', models.ManyToManyField(blank=True, to='invoice.SingleSalesInvoice')),
                ('saleid', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='sales.salescollection')),
            ],
        ),
    ]
