# Generated by Django 3.2.8 on 2022-03-02 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        ('customers', '0001_initial'),
        ('quotations', '0001_initial'),
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='purchaseInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gstNo', models.CharField(blank=True, max_length=50)),
                ('phNo', models.CharField(blank=True, max_length=50)),
                ('date', models.CharField(blank=True, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseMaterialEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_id', models.CharField(blank=True, max_length=10)),
                ('PurchaseDate', models.CharField(blank=True, max_length=50)),
                ('Site', models.CharField(blank=True, max_length=50)),
                ('UnloadingSite', models.CharField(blank=True, max_length=50)),
                ('MaterialName', models.CharField(blank=True, max_length=50)),
                ('CDC', models.CharField(blank=True, max_length=50, null=True)),
                ('LDC', models.CharField(blank=True, max_length=50, null=True)),
                ('VehicleNo', models.CharField(blank=True, max_length=50, null=True)),
                ('Moisture', models.CharField(blank=True, max_length=50, null=True)),
                ('QuantityType', models.CharField(blank=True, max_length=50, null=True)),
                ('QtyFormula', models.CharField(blank=True, max_length=50, null=True)),
                ('QtyCalc', models.CharField(blank=True, max_length=50, null=True)),
                ('RoundOff', models.CharField(blank=True, max_length=50, null=True)),
                ('Rate', models.CharField(blank=True, max_length=50, null=True)),
                ('Total', models.CharField(blank=True, max_length=50, null=True)),
                ('M3Cft', models.CharField(blank=True, max_length=50, null=True)),
                ('M3Ton', models.CharField(blank=True, max_length=50, null=True)),
                ('GST', models.CharField(blank=True, max_length=50, null=True)),
                ('WithGST', models.CharField(blank=True, max_length=50, null=True)),
                ('SiteSupervisior', models.CharField(blank=True, max_length=50, null=True)),
                ('QC', models.CharField(blank=True, max_length=50, null=True)),
                ('Security', models.CharField(blank=True, max_length=50, null=True)),
                ('Engineer', models.CharField(blank=True, max_length=50, null=True)),
                ('DriverName', models.CharField(blank=True, max_length=50, null=True)),
                ('UnloadingSupervisior', models.CharField(blank=True, max_length=50, null=True)),
                ('ig', models.BooleanField(default=False)),
                ('mat_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='orders.materialorder')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseNetAmount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WithOutGSTNetTotalAmount', models.CharField(blank=True, max_length=50)),
                ('WithGSTNetTotalAmount', models.CharField(blank=True, max_length=50)),
                ('AmountPayyed', models.CharField(blank=True, max_length=50)),
                ('Balance', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseRemainder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GSTFilledInvNo', models.CharField(blank=True, max_length=50)),
                ('GSTFilledScanCopy', models.FileField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/')),
                ('GSTFilledInvReceive', models.CharField(blank=True, max_length=50)),
                ('GSTFilledFiledCheck', models.CharField(blank=True, max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='SinglePurchaseEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='purchase.purchaseinvoice')),
                ('netAmount', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='purchase.purchasenetamount')),
                ('purchaseMaterial', models.ManyToManyField(blank=True, to='purchase.PurchaseMaterialEntry')),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quotations.quotation')),
                ('remainder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchase.purchaseremainder')),
                ('vendorId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendors.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc', models.DateTimeField(auto_now_add=True)),
                ('entries', models.ManyToManyField(blank=True, to='purchase.SinglePurchaseEntry')),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quotations.quotation')),
                ('vendorId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendors.vendor')),
            ],
        ),
    ]
