# Generated by Django 4.0.1 on 2022-03-09 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='singlepurchaseentry',
            name='doc',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
