# Generated by Django 4.0.1 on 2022-03-23 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0002_singlepurchaseentry_doc'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasenetamount',
            name='GstBalance',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='purchasenetamount',
            name='GstPayyed',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='purchasenetamount',
            name='GstTotal',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
