# Generated by Django 3.2.8 on 2022-03-02 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Repayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Collection_Date', models.DateField()),
                ('Payment_Method', models.CharField(choices=[('Cash', 'Cash'), ('Card', 'Card'), ('UPI', 'UPI')], max_length=5)),
                ('Collected_By', models.CharField(max_length=100)),
                ('Amount_Paid', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Principal_Amount', models.CharField(max_length=20)),
                ('Released_Date', models.DateField()),
                ('Maturity_Date', models.DateField()),
                ('EMI_Start_Date', models.DateField()),
                ('EMI_End_Date', models.DateField()),
                ('Repayment_Type', models.CharField(choices=[('Monthly', 'Monthly'), ('3 Months Once', '3 Months Once'), ('6 Months Once', '6 Months Once')], max_length=100)),
                ('Penalty', models.CharField(max_length=20)),
                ('Interest', models.CharField(max_length=20)),
                ('Due_Amount', models.CharField(max_length=20)),
                ('Months_Paid', models.CharField(blank=True, max_length=20, null=True)),
                ('Repayments', models.ManyToManyField(blank=True, to='loan.Repayment')),
            ],
        ),
    ]
