# Generated by Django 3.2.12 on 2022-04-18 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0003_alter_agency_date'),
        ('loan', '0002_loan_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='Agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agency.agency'),
        ),
    ]
