from django.urls import path, include
from rest import views
from rest_framework import routers
 
router = routers.DefaultRouter()
router.register(r'users', views.UsersViewSet)
router.register(r'agency', views.AgencyViewSet)
router.register(r'agency-bank', views.AgencyBankAccountViewSet)
router.register(r'agency-certificate', views.AgencyCertificateViewSet) 
router.register(r'agency-phone', views.AgencyPhoneViewSet) 
router.register(r'notifications', views.NotificationViewSet)
router.register(r'attendances', views.AttendanceViewSet)
router.register(r'vendors', views.VendorsViewSet)
router.register(r'vendor-staff', views.VendorStaffViewSet)
router.register(r'vendor-material-from', views.VendorMaterialFromViewSet)
router.register(r'vendor-sub-location', views.VendorSubLocationViewSet)
router.register(r'vendor-material-supplying', views.VendorMaterialSupplyingViewSet)
router.register(r'vendor-material-to', views.VendorMaterialToViewSet)
router.register(r'vendor-material-quality', views.VendorMaterialQualityViewSet)
router.register(r'products', views.ProductsViewSet)
router.register(r'product-quality', views.ProductQualityViewSet)
router.register(r'latest-price', views.LatestPriceViewSet)
router.register(r'customers', views.CustomersViewSet)
router.register(r'customer-staff', views.CustomerStaffViewSet)
router.register(r'customer-bank-account', views.CustomerBankAccountViewSet)
router.register(r'customer-gst-billing-address', views.CustomerGSTBillingAddressViewSet)
router.register(r'customer-pan', views.CustomerPANNoViewSet)
router.register(r'customer-tin', views.CustomerTINNoViewSet)
router.register(r'customer-certificate', views. CustomerCertifcateViewSet)
router.register(r'customer-branch', views.CustomerBranchViewSet)
router.register(r'customer-delivery-address', views.CustomerDeliverAddressViewSet)
router.register(r'customer-branch-delivery-address', views.CustomerBranchDeliveryAddresViewSet)
router.register(r'customer-phone', views.CustomerPhoneNumberViewSet)
router.register(r'orders', views.OrderViewSet)
router.register(r'po-material-info', views.POMaterialInfoViewSet)
router.register(r'po-number', views.POViewSet)
router.register(r'material-info', views.MaterialInfoWithInfoViewSet)
# router.register(r'orders', views.OrderViewSet)
router.register(r'po-number', views.POViewSet)
router.register(r'purchase-quotations', views.PurchaseQuotationViewSet)
router.register(r'sales-quotations', views.SalesQuotationViewSet)
router.register(r'quotations', views.GetQuotationViewSet)
router.register(r'quicknotes', views.QuickNotesViewSet)
router.register(r'vendor-quo-mat', views.GenVendorQuotationDetailViewSet)
router.register(r'purchase-material-entry', views.GetPurchaseMaterialEntryViewSet)
router.register(r'purchase-remainder', views.GetPurchaseRemainderViewSet)
router.register(r'purchase-net-amount', views.GetPurchaseNetAmountViewSet)
router.register(r'single-purchase-entry', views.GetSinglePurchaseEntryViewSet)
router.register(r'purchase-entry', views.GetPurchaseEntryViewSet)
router.register(r'voucher', views.GetVoucherViewSet) 
router.register(r'vouchers', views.VouchersViewSet)
router.register(r'voucher-signature', views.GetVoucherSignatureViewSet)
router.register(r'signature', views.SignatureViewSet)
router.register(r'sales-customer-info', views.GetCutomerInfoViewSet)
router.register(r'sales-material-info', views.GetSalesMaterialInfoViewSet)
router.register(r'sales', views.GetSalesViewSet)
router.register(r'dc-detail', views.GetDCDetailViewSet)
router.register(r'single-invoice', views.GetSingleSalesInvoiceViewSet)
router.register(r'sale-invoice', views.GetSalesInvoiceViewSet)
router.register(r'loans', views.LoanViewSet)
router.register(r'loan-repayment', views.RepaymentViewSet)
router.register(r'bank-entries', views.BankEntryViewSet)
router.register(r'expences', views.ExpencesViewSet)
router.register(r'expence-category', views.ExpenceCategoriesViewSet)
router.register(r'assets', views.AssetsViewSet)

urlpatterns = [
    path('', include(router.urls)),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
]
