# Generated by Django 4.1 on 2022-10-23 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barosatax_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Callback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=225)),
                ('email', models.EmailField(blank=True, max_length=225)),
                ('phone', models.CharField(blank=True, max_length=225)),
                ('service', models.CharField(blank=True, max_length=225)),
                ('message', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=225)),
                ('last_name', models.CharField(blank=True, max_length=225)),
                ('email', models.EmailField(blank=True, max_length=225)),
                ('phone', models.CharField(blank=True, max_length=225)),
                ('service', models.CharField(blank=True, max_length=225)),
                ('message', models.TextField(blank=True)),
            ],
        ),
    ]
